apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: chatbot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: chatbot/frontend:latest
        ports:
        - containerPort: 8501
        env:
        - name: GATEWAY_URL
          value: "http://gateway-service:8000"
        livenessProbe:
          httpGet:
            path: /
            port: 8501
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8501
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: chatbot
spec:
  selector:
    app: frontend
  ports:
  - port: 8501
    targetPort: 8501
  type: LoadBalancer